sudo: required
services:
  - docker

before_install:
  - docker build -t Giuseppe5910/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Giuseppe5910/docker-react npm run test -- --coverage
  